controller_manager:
  ros__parameters:
    update_rate: 1000

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    mimic_joint_controller_LF:
      type: position_controllers/JointGroupPositionController
    mimic_joint_controller_LH:
      type: position_controllers/JointGroupPositionController
    mimic_joint_controller_RH:
      type: position_controllers/JointGroupPositionController
    mimic_joint_controller_RF:
      type: position_controllers/JointGroupPositionController
    
    mimic_joint_controller_LF:
      ros_parameters:
        joints:
          - LF_F1_H2P1
          - LF_F1_P12P2
          - LF_F1_P22P3
          - LF_F2_H2P1
          - LF_F2_P12P2
          - LF_F2_P22P3
          - LF_F3_H2P1
          - LF_F3_P12P2
          - LF_F3_P22P3
          - LF_F4_H2P1
          - LF_F4_P12P2
          - LF_F4_P22P3
          - LF_F5_H2P1
          - LF_F5_P12P2
          - LF_F5_P22P3
          - LF_F6_H2P1
          - LF_F6_P12P2
          - LF_F6_P22P3
          - LF_F7_H2P1
          - LF_F7_P12P2
          - LF_F7_P22P3
          - LF_F8_H2P1
          - LF_F8_P12P2
          - LF_F8_P22P3

    mimic_joint_controller_LH:
      ros_parameters:
        joints:
          - LH_F1_H2P1
          - LH_F1_P12P2
          - LH_F1_P22P3
          - LH_F2_H2P1
          - LH_F2_P12P2
          - LH_F2_P22P3
          - LH_F3_H2P1
          - LH_F3_P12P2
          - LH_F3_P22P3
          - LH_F4_H2P1
          - LH_F4_P12P2
          - LH_F4_P22P3
          - LH_F5_H2P1
          - LH_F5_P12P2
          - LH_F5_P22P3
          - LH_F6_H2P1
          - LH_F6_P12P2
          - LH_F6_P22P3
          - LH_F7_H2P1
          - LH_F7_P12P2
          - LH_F7_P22P3
          - LH_F8_H2P1
          - LH_F8_P12P2
          - LH_F8_P22P3
    mimic_joint_controller_RH:
      ros_parameters:
        joints:
          - RH_F1_H2P1
          - RH_F1_P12P2
          - RH_F1_P22P3
          - RH_F2_H2P1
          - RH_F2_P12P2
          - RH_F2_P22P3
          - RH_F3_H2P1
          - RH_F3_P12P2
          - RH_F3_P22P3
          - RH_F4_H2P1
          - RH_F4_P12P2
          - RH_F4_P22P3
          - RH_F5_H2P1
          - RH_F5_P12P2
          - RH_F5_P22P3
          - RH_F6_H2P1
          - RH_F6_P12P2
          - RH_F6_P22P3
          - RH_F7_H2P1
          - RH_F7_P12P2
          - RH_F7_P22P3
          - RH_F8_H2P1
          - RH_F8_P12P2
          - RH_F8_P22P3

    mimic_joint_controller_RF:
      ros_parameters:
        joints:
          - RF_F1_H2P1
          - RF_F1_P12P2
          - RF_F1_P22P3
          - RF_F2_H2P1
          - RF_F2_P12P2
          - RF_F2_P22P3
          - RF_F3_H2P1
          - RF_F3_P12P2
          - RF_F3_P22P3
          - RF_F4_H2P1
          - RF_F4_P12P2
          - RF_F4_P22P3
          - RF_F5_H2P1
          - RF_F5_P12P2
          - RF_F5_P22P3
          - RF_F6_H2P1
          - RF_F6_P12P2
          - RF_F6_P22P3
          - RF_F7_H2P1
          - RF_F7_P12P2
          - RF_F7_P22P3
          - RF_F8_H2P1
          - RF_F8_P12P2
          - RF_F8_P22P3