controller_manager:
  ros__parameters:
    update_rate: 1000

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # Controls the gripper
    grieel_action_controller_LF:
      type: position_controllers/GripperActionController
    grieel_action_controller_LH:
      type: position_controllers/GripperActionController
    grieel_action_controller_RH:
      type: position_controllers/GripperActionController
    grieel_action_controller_RF:
      type: position_controllers/GripperActionController
    
grieel_action_controller_LF:
  ros__parameters:
    joint: LF_F1_H2P1
    action_monitor_rate: 20.0
    goal_tolerance: 0.01
    max_effort: 100.0
    allow_stalling: false
    stall_velocity_threshold: 0.001
    stall_timeout: 1.0

grieel_action_controller_LH:
  ros__parameters:
    joint: LH_F1_H2P1
    action_monitor_rate: 20.0
    goal_tolerance: 0.01
    max_effort: 100.0
    allow_stalling: false
    stall_velocity_threshold: 0.001
    stall_timeout: 1.0

grieel_action_controller_RH:
  ros__parameters:
    joint: RH_F1_H2P1
    action_monitor_rate: 20.0
    goal_tolerance: 0.01
    max_effort: 100.0
    allow_stalling: false
    stall_velocity_threshold: 0.001
    stall_timeout: 1.0
grieel_action_controller_RF:
  ros__parameters:
    joint: RF_F1_H2P1
    action_monitor_rate: 20.0
    goal_tolerance: 0.01
    max_effort: 100.0
    allow_stalling: false
    stall_velocity_threshold: 0.001
    stall_timeout: 1.0